export const SEARCH_REPOSITORIES = 'SEARCH_REPOSITORIES';
export const SEARCH_REPOSITORIES_SUCCESS = 'SEARCH_REPOSITORIES_SUCCESS';
export const SEARCH_REPOSITORIES_FAILURE = 'SEARCH_REPOSITORIES_FAILURE';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';

